openapi: 3.1.0
info:
  title: STD24044
  description: This is a specification of STD24044
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
    /ping:
      get:
        responses:
          200:
            description: pong
            content:
              text/plain:
                schema:
                  type: string
                  example: pong



    /cars:
      get:
        responses:
          200:
            description: List of posts
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      identifier:
                        type: string
                      brand:
                        type: string
                      model:
                        type: string
          404:
            description: car not found




